const FORMS = {
  total: {
    key: "total",
    name: "Total Concentration",
    gradient: "from-amber-300 via-amber-500 to-yellow-600",
    icon: Brain,
    xp: 5,
    description: "Foundation. Box breathing to stabilize mind & body.",
    pattern: [
      { phase: "Inhale", sec: 4 },
      { phase: "Hold",   sec: 4 },
      { phase: "Exhale", sec: 4 },
      { phase: "Hold",   sec: 4 },
    ],
    cycles: 10,
  },
  water: {
    key: "water",
    name: "Water Breathing",
    gradient: "from-sky-300 via-sky-500 to-blue-600",
    icon: Waves,
    xp: 10,
    description: "Flow & focus. Smooth inhale → longer exhale.",
    pattern: [
      { phase: "Inhale", sec: 4 },
      { phase: "Exhale", sec: 6 },
    ],
    cycles: 8,
  },
  thunder: {
    key: "thunder",
    name: "Thunder Breathing",
    gradient: "from-yellow-300 via-amber-400 to-orange-500",
    icon: Lightning,
    xp: 15,
    description: "Explosive power. Sharp exhales on effort.",
    pattern: [
      { phase: "Inhale", sec: 2 },
      { phase: "Exhale", sec: 2 },
    ],
    cycles: 15,
  },
  wind: {
    key: "wind",
    name: "Wind Breathing",
    gradient: "from-emerald-300 via-green-500 to-lime-600",
    icon: Wind,
    xp: 10,
    description: "Endurance. Longer exhale to recover.",
    pattern: [
      { phase: "Inhale", sec: 4 },
      { phase: "Exhale", sec: 8 },
    ],
    cycles: 10,
  },
  flower: {
    key: "flower",
    name: "Flower Breathing",
    gradient: "from-pink-300 via-rose-500 to-fuchsia-600",
    icon: Flower2,
    xp: 20,
    description: "Calm precision. 4-7-8 nerve-calming breath.",
    pattern: [
      { phase: "Inhale", sec: 4 },
      { phase: "Hold",   sec: 7 },
      { phase: "Exhale", sec: 8 },
    ],
    cycles: 4,
  },
  flame: {
    key: "flame",
    name: "Flame Breathing",
    gradient: "from-orange-300 via-red-500 to-red-700",
    icon: Flame,
    xp: 25,
    description: "Energy & confidence. Short bursts (Breath of Fire).",
    // 20 x 1-second bursts
    pattern: Array.from({ length: 20 }, () => ({ phase: "Burst", sec: 1 })),
    cycles: 1,
  },
};
